[build]
publish = ".next"
command = "yarn build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/locales/en/*.json", "public/locales/de/*.json", "/var/task/next-i18next.config.js"]